version: '3.3'
services:
    mirror-to-gitea:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        environment:
            - GITHUB_USERNAME=github-user
            - GITEA_URL=https://your-gitea.url
            - GITEA_TOKEN=please-exchange-with-token
            # - GITHUB_TOKEN=please-exchange-with-token # Optional, set to mirror private repos
            # - MIRROR_PRIVATE_REPOSITORIES=true # Optional, set to mirror private repos
            # - DELAY=3600 # Optional, set to change the delay between checks (in seconds)
            # - GITEA_ORG_NAME # Optional, set to mirror to an organization instead of a user
        container_name: mirror-to-gitea