version: '3.3'
services:
    mirror-to-gitea:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        env_file:
            - .env
        container_name: mirror-to-gitea
